### ISSUE TITLE
Could not download album art. Error: null

### ISSUE THREAD

**Issue by bjason** [adam-binks/Musical-Wallpaper#1]
The jar worked pretty well several days before, but today an error "Could not download album art. Error: null" occurs. I downloaded the source code and try to run in eclipse (it surely took a long time), and try to find out why. The problem might lies in the dependency. When running to the line:
`Api api = Api.builder() `
the AlbumArtGrabber class instantly reaches to done() method and no following codes run. As a result, when Creator class tries to create the collages, there is no raw material in the Musical Wallpaper folder.
But I should note that when I run the application in eclipse, the error window prompt out in less than one second but when running the jar the error prompt appears after several seconds. While they do share the same error message.
I cannot figure out why this happens as it did made several collages for me days ago. Maybe it is because the API? If there is any usage limit of the Spotify Api as far as you know?

**Comment by adam-binks** [comment]
Hi @bjason - thanks for taking the time to report this and having an investigate!

I did run into a couple of exceptions which were printing null error messages. I just pushed a new release which should hopefully fix these, and also moves to Maven project structure/hierarchy.

I didn't notice any issues with interacting with the API itself, so if you could try running the jar of the new release and let me know whether the bug persists that would be great!
